### ISSUE TITLE
Extension hides JISHO search bar because of generic css class name.

### ISSUE THREAD

**Issue by EtienneDesticourt** [jk2227/chrome-extension#9]
Hi,

In your overlay CSS class you set display to None but overlay is a very generic name and it effectively hides elements from a number of websites that use the same class name. 
For example the JISHO search bar that's wrapped in an overlay div.

I'm in the process of submitting a pull request to fix this particular instance of the bug but generally you probably want to use non generic names for all your css classes.

Cheers.

**Comment by jk2227** [comment]
Merged in 478208e779beb91b391e1ebe28df0ced9978c98b and updating the chrome extension; thanks for the suggestion!
